# local-cluster-deployment.yaml
# This file is used to create a local Kubernetes cluster using KinD (Kubernetes in Docker).
# It defines the cluster configuration, including the control plane and worker nodes.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local-gitops-cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true,istio-injection=disabled"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080 # HTTP traffic via Istio Gateway
    protocol: TCP
  - containerPort: 443
    hostPort: 8443 # HTTPS traffic via Istio Gateway
    protocol: TCP
  - containerPort: 15021
    hostPort: 15021 # Istio health check port
    protocol: TCP
  - containerPort: 15443
    hostPort: 15443 # Istio Gateway HTTPS
    protocol: TCP
  - containerPort: 31400
    hostPort: 31400 # Additional Istio Gateway port
    protocol: TCP
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node-role.kubernetes.io/infra=true"
      taints:
        - key: "node-role.kubernetes.io/infra"
          value: "true"
          effect: "NoSchedule"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node-role.kubernetes.io/apps=true"
      taints:
        - key: "node-role.kubernetes.io/apps"
          value: "true"
          effect: "NoSchedule"